### ISSUE TITLE
crop_and_aug.py giving error

### ISSUE THREAD

**Issue by rakashi** [satojkovic/DeepLogo#10]
Hi, I am trying crop and augment the flickr_logos_27_dataset using below command

(tensorflow)rakashi@pavan:~/PycharmProjects/DeepLogo-master$ python crop_and_aug.py

I am unable to identify what is the problem, Ia musing the libraries list as

Pillow (2.3.0)
numpy (1.13.1)

Traceback (most recent call last):
  File "/home/rakashi/PycharmProjects/DeepLogo-master/crop_and_aug.py", line 313, in <module>
    main()
  File "/home/rakashi/PycharmProjects/DeepLogo-master/crop_and_aug.py", line 306, in main
    crop_and_aug_with_none(annot_train)
  File "/home/rakashi/PycharmProjects/DeepLogo-master/crop_and_aug.py", line 254, in crop_and_aug_with_none
    crop_and_aug(annot_train)
  File "/home/rakashi/PycharmProjects/DeepLogo-master/crop_and_aug.py", line 200, in crop_and_aug
    shifted_ims, shifted_suffixes = aug_pos(annot, im)
  File "/home/rakashi/PycharmProjects/DeepLogo-master/crop_and_aug.py", line 90, in aug_pos
    cropped_im.close()
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: close

**Comment by satojkovic** [comment]
@rakashi 

It seems that Pillow 2.3.0 misses the close method.
Please upgrade Pillow.
